# Generated by Django 3.0.8 on 2020-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
