# Generated by Django 3.0.8 on 2020-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
