# Generated by Django 3.0.8 on 2020-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200808_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
