# Generated by Django 3.0.8 on 2020-08-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200806_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Categories',
            new_name='category',
        ),
    ]
