# Generated by Django 3.0.8 on 2020-08-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200802_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
