# Generated by Django 3.0.8 on 2020-08-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='closed',
            new_name='close',
        ),
    ]
