# Generated by Django 3.0.8 on 2020-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200802_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
